name: Python CI

on:
  push:
    branches:
      - main  # Der Workflow wird ausgeführt, wenn Code auf den main-Branch gepusht wird
  pull_request:
    branches:
      - main  # Der Workflow wird auch für Pull Requests auf den main-Branch ausgeführt

jobs:
  test:
    runs-on: ubuntu-latest  # Verwenden von Ubuntu als Betriebssystem

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Lädt deinen Code herunter
    - name: Set up Python
      uses: actions/setup-python@v2  # Setzt die Python-Version
      with:
        python-version: '3.8'  # Stelle sicher, dass die Version hier korrekt ist
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Installiert alle Abhängigkeiten
    - name: Run tests
      run: |
        pytest  # Führt die Tests aus
